#API key/secret
consumer_key: ALMRmXKozjinNoL8Qk01DbDXw
consumer_secret: 6qIvkxd5ytFrVwZYvVOjcRtoUwTu3huIoRjv4Q7AhZZrXxzaVG
#Access token/secret
access_token: 2877561725-Prx4tzOs2QQAtXtNCJQ7uhDdP2gyIKGiz7vFqpS
access_token_secret: s0C7sb3a2Q49Exzz5DxSSasnXEYfMeFSz11blyhYoy7Dd